//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto for ControlResult
func (in *ControlResult) DeepCopyInto(out *ControlResult) { *out = *in }
func (in *ControlResult) DeepCopy() *ControlResult {
	if in == nil {
		return nil
	}
	out := new(ControlResult)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto for Finding
func (in *Finding) DeepCopyInto(out *Finding) { *out = *in }

// DeepCopyInto for OSDOPolicy
func (in *OSDOPolicy) DeepCopyInto(out *OSDOPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}
func (in *OSDOPolicy) DeepCopy() *OSDOPolicy {
	if in == nil {
		return nil
	}
	out := new(OSDOPolicy)
	in.DeepCopyInto(out)
	return out
}
func (in *OSDOPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto for OSDOPolicyList
func (in *OSDOPolicyList) DeepCopyInto(out *OSDOPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OSDOPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}
func (in *OSDOPolicyList) DeepCopy() *OSDOPolicyList {
	if in == nil {
		return nil
	}
	out := new(OSDOPolicyList)
	in.DeepCopyInto(out)
	return out
}
func (in *OSDOPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto for OSDOPolicySpec
func (in *OSDOPolicySpec) DeepCopyInto(out *OSDOPolicySpec) {
	*out = *in
	if in.RequiredControls != nil {
		in, out := &in.RequiredControls, &out.RequiredControls
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}
func (in *OSDOPolicySpec) DeepCopy() *OSDOPolicySpec {
	if in == nil {
		return nil
	}
	out := new(OSDOPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto for SecurityReport
func (in *SecurityReport) DeepCopyInto(out *SecurityReport) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}
func (in *SecurityReport) DeepCopy() *SecurityReport {
	if in == nil {
		return nil
	}
	out := new(SecurityReport)
	in.DeepCopyInto(out)
	return out
}
func (in *SecurityReport) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto for SecurityReportList
func (in *SecurityReportList) DeepCopyInto(out *SecurityReportList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SecurityReport, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}
func (in *SecurityReportList) DeepCopy() *SecurityReportList {
	if in == nil {
		return nil
	}
	out := new(SecurityReportList)
	in.DeepCopyInto(out)
	return out
}
func (in *SecurityReportList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto for SecurityReportSpec
func (in *SecurityReportSpec) DeepCopyInto(out *SecurityReportSpec) {
	*out = *in
	if in.Controls != nil {
		in, out := &in.Controls, &out.Controls
		*out = make([]ControlResult, len(*in))
		copy(*out, *in)
	}
	if in.Findings != nil {
		in, out := &in.Findings, &out.Findings
		*out = make([]Finding, len(*in))
		copy(*out, *in)
	}
}

// DeepCopyInto for SecurityScan
func (in *SecurityScan) DeepCopyInto(out *SecurityScan) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}
func (in *SecurityScan) DeepCopy() *SecurityScan {
	if in == nil {
		return nil
	}
	out := new(SecurityScan)
	in.DeepCopyInto(out)
	return out
}
func (in *SecurityScan) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto for SecurityScanList
func (in *SecurityScanList) DeepCopyInto(out *SecurityScanList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SecurityScan, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}
func (in *SecurityScanList) DeepCopy() *SecurityScanList {
	if in == nil {
		return nil
	}
	out := new(SecurityScanList)
	in.DeepCopyInto(out)
	return out
}
func (in *SecurityScanList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto for SecurityScanSpec
func (in *SecurityScanSpec) DeepCopyInto(out *SecurityScanSpec) {
	*out = *in
	if in.ScanType != nil {
		in, out := &in.ScanType, &out.ScanType
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopyInto for SecurityScanStatus
func (in *SecurityScanStatus) DeepCopyInto(out *SecurityScanStatus) {
	*out = *in
	if in.StartTime != nil {
		in, out := &in.StartTime, &out.StartTime
		*out = (*in).DeepCopy()
	}
	if in.CompletionTime != nil {
		in, out := &in.CompletionTime, &out.CompletionTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}
